/*
 * Decompiled with CFR 0.152.
 */
package zombie.core.properties;

import zombie.UsedFromLua;
import zombie.scripting.objects.Registries;
import zombie.scripting.objects.RegistryReset;
import zombie.scripting.objects.ResourceLocation;

@UsedFromLua
public final class TilePropertyKey {
    public static final TilePropertyKey ALWAYS_DRAW = TilePropertyKey.registerBase("alwaysDraw");
    public static final TilePropertyKey AMBIENT_SOUND = TilePropertyKey.registerBase("AmbientSound");
    public static final TilePropertyKey ATTACHED_CEILING = TilePropertyKey.registerBase("attachedCeiling");
    public static final TilePropertyKey ATTACHED_E = TilePropertyKey.registerBase("attachedE");
    public static final TilePropertyKey ATTACHED_FLOOR = TilePropertyKey.registerBase("AttachedFloor");
    public static final TilePropertyKey ATTACHED_N = TilePropertyKey.registerBase("attachedN");
    public static final TilePropertyKey ATTACHED_NW = TilePropertyKey.registerBase("attachedNW");
    public static final TilePropertyKey ATTACHED_S = TilePropertyKey.registerBase("attachedS");
    public static final TilePropertyKey ATTACHED_SE = TilePropertyKey.registerBase("attachedSE");
    public static final TilePropertyKey ATTACHED_SURFACE = TilePropertyKey.registerBase("attachedSurface");
    public static final TilePropertyKey ATTACHED_TO_GLASS = TilePropertyKey.registerBase("AttachedToGlass");
    public static final TilePropertyKey ATTACHED_W = TilePropertyKey.registerBase("attachedW");
    public static final TilePropertyKey ATTACH_TO_STAIRS = TilePropertyKey.registerBase("attachtostairs");
    public static final TilePropertyKey BED = TilePropertyKey.registerBase("bed");
    public static final TilePropertyKey BED_TYPE = TilePropertyKey.registerBase("BedType");
    public static final TilePropertyKey BLOCKS_PLACEMENT = TilePropertyKey.registerBase("BlocksPlacement");
    public static final TilePropertyKey BLOCK_RAIN = TilePropertyKey.registerBase("BlockRain");
    public static final TilePropertyKey BLOCK_SIGHT = TilePropertyKey.registerBase("blocksight");
    public static final TilePropertyKey BLUEPRINT = TilePropertyKey.registerBase("blueprint");
    public static final TilePropertyKey BURNING = TilePropertyKey.registerBase("burning");
    public static final TilePropertyKey BURNT_OUT = TilePropertyKey.registerBase("burntOut");
    public static final TilePropertyKey BURNT_TILE = TilePropertyKey.registerBase("BurntTile");
    public static final TilePropertyKey BUSH = TilePropertyKey.registerBase("Bush");
    public static final TilePropertyKey CANT_CLIMB = TilePropertyKey.registerBase("CantClimb");
    public static final TilePropertyKey CAN_ATTACH_ANIMAL = TilePropertyKey.registerBase("CanAttachAnimal");
    public static final TilePropertyKey CAN_BE_CUT = TilePropertyKey.registerBase("canBeCut");
    public static final TilePropertyKey CAN_BE_REMOVED = TilePropertyKey.registerBase("canBeRemoved");
    public static final TilePropertyKey CAN_BREAK = TilePropertyKey.registerBase("CanBreak");
    public static final TilePropertyKey CAN_PATH_N = TilePropertyKey.registerBase("canPathN");
    public static final TilePropertyKey CAN_PATH_W = TilePropertyKey.registerBase("canPathW");
    public static final TilePropertyKey CAN_SCRAP = TilePropertyKey.registerBase("CanScrap");
    public static final TilePropertyKey CAR_SLOW_FACTOR = TilePropertyKey.registerBase("CarSlowFactor");
    public static final TilePropertyKey CHAIR_E = TilePropertyKey.registerBase("chairE");
    public static final TilePropertyKey CHAIR_N = TilePropertyKey.registerBase("chairN");
    public static final TilePropertyKey CHAIR_S = TilePropertyKey.registerBase("chairS");
    public static final TilePropertyKey CHAIR_W = TilePropertyKey.registerBase("chairW");
    public static final TilePropertyKey CLIMB_SHEET_E = TilePropertyKey.registerBase("climbSheetE");
    public static final TilePropertyKey CLIMB_SHEET_N = TilePropertyKey.registerBase("climbSheetN");
    public static final TilePropertyKey CLIMB_SHEET_S = TilePropertyKey.registerBase("climbSheetS");
    public static final TilePropertyKey CLIMB_SHEET_TOP_E = TilePropertyKey.registerBase("climbSheetTopE");
    public static final TilePropertyKey CLIMB_SHEET_TOP_N = TilePropertyKey.registerBase("climbSheetTopN");
    public static final TilePropertyKey CLIMB_SHEET_TOP_S = TilePropertyKey.registerBase("climbSheetTopS");
    public static final TilePropertyKey CLIMB_SHEET_TOP_W = TilePropertyKey.registerBase("climbSheetTopW");
    public static final TilePropertyKey CLIMB_SHEET_W = TilePropertyKey.registerBase("climbSheetW");
    public static final TilePropertyKey CLOSE_SNEAK_BONUS = TilePropertyKey.registerBase("CloseSneakBonus");
    public static final TilePropertyKey COLLIDE_N = TilePropertyKey.registerBase("collideN");
    public static final TilePropertyKey COLLIDE_W = TilePropertyKey.registerBase("collideW");
    public static final TilePropertyKey CONNECT_X = TilePropertyKey.registerBase("connectX");
    public static final TilePropertyKey CONNECT_Y = TilePropertyKey.registerBase("connectY");
    public static final TilePropertyKey CONTAINER = TilePropertyKey.registerBase("container");
    public static final TilePropertyKey CONTAINER_CAPACITY = TilePropertyKey.registerBase("ContainerCapacity");
    public static final TilePropertyKey CONTAINER_CLOSE_SOUND = TilePropertyKey.registerBase("ContainerCloseSound");
    public static final TilePropertyKey CONTAINER_OPEN_SOUND = TilePropertyKey.registerBase("ContainerOpenSound");
    public static final TilePropertyKey CONTAINER_POSITION = TilePropertyKey.registerBase("ContainerPosition");
    public static final TilePropertyKey CONTAINER_PUT_SOUND = TilePropertyKey.registerBase("ContainerPutSound");
    public static final TilePropertyKey CONTAINER_TAKE_SOUND = TilePropertyKey.registerBase("ContainerTakeSound");
    public static final TilePropertyKey CORNER_NORTH_WALL = TilePropertyKey.registerBase("CornerNorthWall");
    public static final TilePropertyKey CORNER_WEST_WALL = TilePropertyKey.registerBase("CornerWestWall");
    public static final TilePropertyKey CURTAIN_E = TilePropertyKey.registerBase("curtainE");
    public static final TilePropertyKey CURTAIN_N = TilePropertyKey.registerBase("curtainN");
    public static final TilePropertyKey CURTAIN_OFFSET = TilePropertyKey.registerBase("CurtainOffset");
    public static final TilePropertyKey CURTAIN_S = TilePropertyKey.registerBase("curtainS");
    public static final TilePropertyKey CURTAIN_SOUND = TilePropertyKey.registerBase("CurtainSound");
    public static final TilePropertyKey CURTAIN_W = TilePropertyKey.registerBase("curtainW");
    public static final TilePropertyKey CUSTOM_ITEM = TilePropertyKey.registerBase("CustomItem");
    public static final TilePropertyKey CUSTOM_NAME = TilePropertyKey.registerBase("CustomName");
    public static final TilePropertyKey CUTAWAY_HINT = TilePropertyKey.registerBase("CutawayHint");
    public static final TilePropertyKey CUT_N = TilePropertyKey.registerBase("cutN");
    public static final TilePropertyKey CUT_W = TilePropertyKey.registerBase("cutW");
    public static final TilePropertyKey DAMAGED_SPRITE = TilePropertyKey.registerBase("DamagedSprite");
    public static final TilePropertyKey DIAMOND_FLOOR = TilePropertyKey.registerBase("diamondFloor");
    public static final TilePropertyKey DOOR_FR_N = TilePropertyKey.registerBase("doorFrN");
    public static final TilePropertyKey DOOR_FR_W = TilePropertyKey.registerBase("doorFrW");
    public static final TilePropertyKey DOOR_N = TilePropertyKey.registerBase("doorN");
    public static final TilePropertyKey DOOR_SOUND = TilePropertyKey.registerBase("DoorSound");
    public static final TilePropertyKey DOOR_TRANS = TilePropertyKey.registerBase("doorTrans");
    public static final TilePropertyKey DOOR_W = TilePropertyKey.registerBase("doorW");
    public static final TilePropertyKey DOOR_WALL_N = TilePropertyKey.registerBase("DoorWallN");
    public static final TilePropertyKey DOOR_WALL_NW = TilePropertyKey.registerBase("DoorWallNW");
    public static final TilePropertyKey DOOR_WALL_NW_TRANS = TilePropertyKey.registerBase("DoorWallNWTrans");
    public static final TilePropertyKey DOOR_WALL_N_TRANS = TilePropertyKey.registerBase("DoorWallNTrans");
    public static final TilePropertyKey DOOR_WALL_W = TilePropertyKey.registerBase("DoorWallW");
    public static final TilePropertyKey DOOR_WALL_W_TRANS = TilePropertyKey.registerBase("DoorWallWTrans");
    public static final TilePropertyKey DOUBLE_DOOR = TilePropertyKey.registerBase("DoubleDoor");
    public static final TilePropertyKey DOUBLE_DOOR_1 = TilePropertyKey.registerBase("DoubleDoor1");
    public static final TilePropertyKey DOUBLE_DOOR_2 = TilePropertyKey.registerBase("DoubleDoor2");
    public static final TilePropertyKey ENTITY_SCRIPT = TilePropertyKey.registerBase("EntityScript");
    public static final TilePropertyKey ENTITY_SCRIPT_NAME = TilePropertyKey.registerBase("EntityScriptName");
    public static final TilePropertyKey EXTERIOR = TilePropertyKey.registerBase("exterior");
    public static final TilePropertyKey E_OFFSET = TilePropertyKey.registerBase("Eoffset");
    public static final TilePropertyKey FACING = TilePropertyKey.registerBase("Facing");
    public static final TilePropertyKey FASCIA_EDGE = TilePropertyKey.registerBase("FasciaEdge");
    public static final TilePropertyKey FASCIA_EDGE_REVERSIBLE = TilePropertyKey.registerBase("FasciaEdgeReversible");
    public static final TilePropertyKey FENCE_TYPE_HIGH = TilePropertyKey.registerBase("FenceTypeHigh");
    public static final TilePropertyKey FENCE_TYPE_LOW = TilePropertyKey.registerBase("FenceTypeLow");
    public static final TilePropertyKey FIRE_REQUIREMENT = TilePropertyKey.registerBase("firerequirement");
    public static final TilePropertyKey FLOOR_ATTACHMENT_E = TilePropertyKey.registerBase("FloorAttachmentE");
    public static final TilePropertyKey FLOOR_ATTACHMENT_N = TilePropertyKey.registerBase("FloorAttachmentN");
    public static final TilePropertyKey FLOOR_ATTACHMENT_S = TilePropertyKey.registerBase("FloorAttachmentS");
    public static final TilePropertyKey FLOOR_ATTACHMENT_W = TilePropertyKey.registerBase("FloorAttachmentW");
    public static final TilePropertyKey FLOOR_HEIGHT = TilePropertyKey.registerBase("FloorHeight");
    public static final TilePropertyKey FLOOR_HEIGHT_ONE_THIRD = TilePropertyKey.registerBase("FloorHeightOneThird");
    public static final TilePropertyKey FLOOR_HEIGHT_TWO_THIRDS = TilePropertyKey.registerBase("FloorHeightTwoThirds");
    public static final TilePropertyKey FLOOR_MATERIAL = TilePropertyKey.registerBase("FloorMaterial");
    public static final TilePropertyKey FLOOR_OVERLAY = TilePropertyKey.registerBase("FloorOverlay");
    public static final TilePropertyKey FOOTSTEP_MATERIAL = TilePropertyKey.registerBase("FootstepMaterial");
    public static final TilePropertyKey FORCED_LOCKED = TilePropertyKey.registerBase("forcedLocked");
    public static final TilePropertyKey FORCE_AMBIENT = TilePropertyKey.registerBase("ForceAmbient");
    public static final TilePropertyKey FORCE_FADE = TilePropertyKey.registerBase("forceFade");
    public static final TilePropertyKey FORCE_LOCKED = TilePropertyKey.registerBase("forceLocked");
    public static final TilePropertyKey FORCE_RENDER = TilePropertyKey.registerBase("forceRender");
    public static final TilePropertyKey FORCE_SINGLE_ITEM = TilePropertyKey.registerBase("ForceSingleItem");
    public static final TilePropertyKey FREEZER = TilePropertyKey.registerBase("Freezer");
    public static final TilePropertyKey FREEZER_CAPACITY = TilePropertyKey.registerBase("FreezerCapacity");
    public static final TilePropertyKey FREEZER_POSITION = TilePropertyKey.registerBase("FreezerPosition");
    public static final TilePropertyKey FUEL_AMOUNT = TilePropertyKey.registerBase("fuelAmount");
    public static final TilePropertyKey GARAGE_DOOR = TilePropertyKey.registerBase("GarageDoor");
    public static final TilePropertyKey GENERATOR_SOUND = TilePropertyKey.registerBase("GeneratorSound");
    public static final TilePropertyKey GENERIC_CRAFTING_SURFACE = TilePropertyKey.registerBase("GenericCraftingSurface");
    public static final TilePropertyKey GLASS_REMOVED_OFFSET = TilePropertyKey.registerBase("GlassRemovedOffset");
    public static final TilePropertyKey GRASS_FLOOR = TilePropertyKey.registerBase("grassFloor");
    public static final TilePropertyKey GRIME_TYPE = TilePropertyKey.registerBase("GrimeType");
    public static final TilePropertyKey GROUP_NAME = TilePropertyKey.registerBase("GroupName");
    public static final TilePropertyKey HALF_HEIGHT = TilePropertyKey.registerBase("halfheight");
    public static final TilePropertyKey HAS_LIGHT_ON_SPRITE = TilePropertyKey.registerBase("HasLightOnSprite");
    public static final TilePropertyKey HAS_RAINDROP = TilePropertyKey.registerBase("HasRaindrop");
    public static final TilePropertyKey HAS_RAIN_SPLASHES = TilePropertyKey.registerBase("HasRainSplashes");
    public static final TilePropertyKey HIDE_WALLS = TilePropertyKey.registerBase("hidewalls");
    public static final TilePropertyKey HIT_BY_CAR = TilePropertyKey.registerBase("HitByCar");
    public static final TilePropertyKey HOPPABLE_N = TilePropertyKey.registerBase("HoppableN");
    public static final TilePropertyKey HOPPABLE_W = TilePropertyKey.registerBase("HoppableW");
    public static final TilePropertyKey IGNORE_SURFACE_SNAP = TilePropertyKey.registerBase("IgnoreSurfaceSnap");
    public static final TilePropertyKey INTERIOR = TilePropertyKey.registerBase("interior");
    public static final TilePropertyKey INTERIOR_SIDE = TilePropertyKey.registerBase("InteriorSide");
    public static final TilePropertyKey INVISIBLE = TilePropertyKey.registerBase("invisible");
    public static final TilePropertyKey ISO_TYPE = TilePropertyKey.registerBase("IsoType");
    public static final TilePropertyKey IS_CLOSED_STATE = TilePropertyKey.registerBase("IsClosedState");
    public static final TilePropertyKey IS_EAVE = TilePropertyKey.registerBase("isEave");
    public static final TilePropertyKey IS_FLOOR_ATTACHED = TilePropertyKey.registerBase("IsFloorAttached");
    public static final TilePropertyKey IS_FRIDGE = TilePropertyKey.registerBase("IsFridge");
    public static final TilePropertyKey IS_GRID_EXTENSION_TILE = TilePropertyKey.registerBase("IsGridExtensionTile");
    public static final TilePropertyKey IS_HIGH = TilePropertyKey.registerBase("IsHigh");
    public static final TilePropertyKey IS_LOW = TilePropertyKey.registerBase("IsLow");
    public static final TilePropertyKey IS_MIRROR = TilePropertyKey.registerBase("IsMirror");
    public static final TilePropertyKey IS_MOVE_ABLE = TilePropertyKey.registerBase("IsMoveAble");
    public static final TilePropertyKey IS_MOVE_ABLE_OBJECT = TilePropertyKey.registerBase("isMoveAbleObject");
    public static final TilePropertyKey IS_PAINTABLE = TilePropertyKey.registerBase("IsPaintable");
    public static final TilePropertyKey IS_STACKABLE = TilePropertyKey.registerBase("IsStackable");
    public static final TilePropertyKey IS_SURFACE_OFFSET = TilePropertyKey.registerBase("IsSurfaceOffset");
    public static final TilePropertyKey IS_TABLE = TilePropertyKey.registerBase("IsTable");
    public static final TilePropertyKey IS_TABLE_TOP = TilePropertyKey.registerBase("IsTableTop");
    public static final TilePropertyKey IS_TRASH_CAN = TilePropertyKey.registerBase("IsTrashCan");
    public static final TilePropertyKey IS_WATER_COLLECTOR = TilePropertyKey.registerBase("IsWaterCollector");
    public static final TilePropertyKey ITEM_HEIGHT = TilePropertyKey.registerBase("ItemHeight");
    public static final TilePropertyKey JUKEBOX = TilePropertyKey.registerBase("jukebox");
    public static final TilePropertyKey LIGHTSWITCH = TilePropertyKey.registerBase("lightswitch");
    public static final TilePropertyKey LIGHT_B = TilePropertyKey.registerBase("lightB");
    public static final TilePropertyKey LIGHT_FILTER_B = TilePropertyKey.registerBase("LightFilterB");
    public static final TilePropertyKey LIGHT_FILTER_G = TilePropertyKey.registerBase("LightFilterG");
    public static final TilePropertyKey LIGHT_FILTER_INTENSITY = TilePropertyKey.registerBase("LightFilterIntensity");
    public static final TilePropertyKey LIGHT_FILTER_MIX = TilePropertyKey.registerBase("LightFilterMix");
    public static final TilePropertyKey LIGHT_FILTER_R = TilePropertyKey.registerBase("LightFilterR");
    public static final TilePropertyKey LIGHT_G = TilePropertyKey.registerBase("lightG");
    public static final TilePropertyKey LIGHT_R = TilePropertyKey.registerBase("lightR");
    public static final TilePropertyKey LIGHT_RADIUS = TilePropertyKey.registerBase("LightRadius");
    public static final TilePropertyKey LINKED_LOC_IS = TilePropertyKey.registerBase("LinkedLocIs");
    public static final TilePropertyKey LINKED_OFFSET = TilePropertyKey.registerBase("LinkedOffset");
    public static final TilePropertyKey LIVING_ROOM = TilePropertyKey.registerBase("livingRoom");
    public static final TilePropertyKey MAKE_WINDOW_INVINCIBLE = TilePropertyKey.registerBase("makeWindowInvincible");
    public static final TilePropertyKey MATERIAL = TilePropertyKey.registerBase("Material");
    public static final TilePropertyKey MATERIAL_2 = TilePropertyKey.registerBase("Material2");
    public static final TilePropertyKey MATERIAL_3 = TilePropertyKey.registerBase("Material3");
    public static final TilePropertyKey MATERIAL_TYPE = TilePropertyKey.registerBase("MaterialType");
    public static final TilePropertyKey MICROWAVE = TilePropertyKey.registerBase("Microwave");
    public static final TilePropertyKey MINIMUM_CAR_SPEED_DMG = TilePropertyKey.registerBase("MinimumCarSpeedDmg");
    public static final TilePropertyKey MOVEMENT = TilePropertyKey.registerBase("Movement");
    public static final TilePropertyKey MOVE_TYPE = TilePropertyKey.registerBase("MoveType");
    public static final TilePropertyKey MOVE_WITH_WIND = TilePropertyKey.registerBase("MoveWithWind");
    public static final TilePropertyKey NAME = TilePropertyKey.registerBase("name");
    public static final TilePropertyKey NATURE_FLOOR = TilePropertyKey.registerBase("natureFloor");
    public static final TilePropertyKey NEVER_CUTAWAY = TilePropertyKey.registerBase("NeverCutaway");
    public static final TilePropertyKey NO_FREEZER = TilePropertyKey.registerBase("NoFreezer");
    public static final TilePropertyKey NO_START = TilePropertyKey.registerBase("noStart");
    public static final TilePropertyKey NO_WALL_LIGHTING = TilePropertyKey.registerBase("NoWallLighting");
    public static final TilePropertyKey N_OFFSET = TilePropertyKey.registerBase("Noffset");
    public static final TilePropertyKey OPAQUE_PIXELS_ONLY = TilePropertyKey.registerBase("OpaquePixelsOnly");
    public static final TilePropertyKey OPEN = TilePropertyKey.registerBase("open");
    public static final TilePropertyKey OPEN_TILE_OFFSET = TilePropertyKey.registerBase("OpenTileOffset");
    public static final TilePropertyKey PAINTING_TYPE = TilePropertyKey.registerBase("PaintingType");
    public static final TilePropertyKey PHYSICS_MESH = TilePropertyKey.registerBase("PhysicsMesh");
    public static final TilePropertyKey PHYSICS_SHAPE = TilePropertyKey.registerBase("PhysicsShape");
    public static final TilePropertyKey PICK_UP_LEVEL = TilePropertyKey.registerBase("PickUpLevel");
    public static final TilePropertyKey PICK_UP_TOOL = TilePropertyKey.registerBase("PickUpTool");
    public static final TilePropertyKey PICK_UP_WEIGHT = TilePropertyKey.registerBase("PickUpWeight");
    public static final TilePropertyKey PLACE_TOOL = TilePropertyKey.registerBase("PlaceTool");
    public static final TilePropertyKey PROPANE_TANK = TilePropertyKey.registerBase("propaneTank");
    public static final TilePropertyKey RADIO = TilePropertyKey.registerBase("radio");
    public static final TilePropertyKey RENDER_LAYER = TilePropertyKey.registerBase("RenderLayer");
    public static final TilePropertyKey ROOF_GROUP = TilePropertyKey.registerBase("RoofGroup");
    public static final TilePropertyKey SCRAP_SIZE = TilePropertyKey.registerBase("ScrapSize");
    public static final TilePropertyKey SCRAP_TOOL_USE_OVERRIDE = TilePropertyKey.registerBase("ScrapToolUseOverride");
    public static final TilePropertyKey SCRAP_USE_SKILL = TilePropertyKey.registerBase("ScrapUseSkill");
    public static final TilePropertyKey SCRAP_USE_TOOL = TilePropertyKey.registerBase("ScrapUseTool");
    public static final TilePropertyKey SEAT_MATERIAL = TilePropertyKey.registerBase("SeatMaterial");
    public static final TilePropertyKey SIGNAL = TilePropertyKey.registerBase("signal");
    public static final TilePropertyKey SINK_TYPE = TilePropertyKey.registerBase("SinkType");
    public static final TilePropertyKey SLOPED_SURFACE_DIRECTION = TilePropertyKey.registerBase("SlopedSurfaceDirection");
    public static final TilePropertyKey SLOPED_SURFACE_HEIGHT_MAX = TilePropertyKey.registerBase("SlopedSurfaceHeightMax");
    public static final TilePropertyKey SLOPED_SURFACE_HEIGHT_MIN = TilePropertyKey.registerBase("SlopedSurfaceHeightMin");
    public static final TilePropertyKey SMASHED_TILE_OFFSET = TilePropertyKey.registerBase("SmashedTileOffset");
    public static final TilePropertyKey SMOKE = TilePropertyKey.registerBase("smoke");
    public static final TilePropertyKey SNOW_TILE = TilePropertyKey.registerBase("SnowTile");
    public static final TilePropertyKey SOLID = TilePropertyKey.registerBase("solid");
    public static final TilePropertyKey SOLID_FLOOR = TilePropertyKey.registerBase("solidfloor");
    public static final TilePropertyKey SOLID_TRANS = TilePropertyKey.registerBase("solidtrans");
    public static final TilePropertyKey SPEAR_ONLY_ATTACK_THROUGH = TilePropertyKey.registerBase("SpearOnlyAttackThrough");
    public static final TilePropertyKey SPRITE_GRID_LEVEL = TilePropertyKey.registerBase("SpriteGridLevel");
    public static final TilePropertyKey SPRITE_GRID_POS = TilePropertyKey.registerBase("SpriteGridPos");
    public static final TilePropertyKey STACK_REPLACE_TILE_OFFSET = TilePropertyKey.registerBase("StackReplaceTileOffset");
    public static final TilePropertyKey STAIRS_BN = TilePropertyKey.registerBase("stairsBN");
    public static final TilePropertyKey STAIRS_BW = TilePropertyKey.registerBase("stairsBW");
    public static final TilePropertyKey STAIRS_MN = TilePropertyKey.registerBase("stairsMN");
    public static final TilePropertyKey STAIRS_MW = TilePropertyKey.registerBase("stairsMW");
    public static final TilePropertyKey STAIRS_TN = TilePropertyKey.registerBase("stairsTN");
    public static final TilePropertyKey STAIRS_TW = TilePropertyKey.registerBase("stairsTW");
    public static final TilePropertyKey STOP_CAR = TilePropertyKey.registerBase("StopCar");
    public static final TilePropertyKey STREETLIGHT = TilePropertyKey.registerBase("streetlight");
    public static final TilePropertyKey SURFACE = TilePropertyKey.registerBase("Surface");
    public static final TilePropertyKey S_OFFSET = TilePropertyKey.registerBase("Soffset");
    public static final TilePropertyKey TABLE_N = TilePropertyKey.registerBase("tableN");
    public static final TilePropertyKey TAINTED_WATER = TilePropertyKey.registerBase("taintedWater");
    public static final TilePropertyKey TALL_HOPPABLE_N = TilePropertyKey.registerBase("TallHoppableN");
    public static final TilePropertyKey TALL_HOPPABLE_W = TilePropertyKey.registerBase("TallHoppableW");
    public static final TilePropertyKey THUMP_SOUND = TilePropertyKey.registerBase("ThumpSound");
    public static final TilePropertyKey TIE_SHEET_ROPE = TilePropertyKey.registerBase("TieSheetRope");
    public static final TilePropertyKey TILE_OVERLAY = TilePropertyKey.registerBase("TileOverlay");
    public static final TilePropertyKey TRANS = TilePropertyKey.registerBase("trans");
    public static final TilePropertyKey TRANSLUCENT = TilePropertyKey.registerBase("Translucent");
    public static final TilePropertyKey TRANSPARENT_FLOOR = TilePropertyKey.registerBase("transparentFloor");
    public static final TilePropertyKey TRANSPARENT_N = TilePropertyKey.registerBase("transparentN");
    public static final TilePropertyKey TRANSPARENT_W = TilePropertyKey.registerBase("transparentW");
    public static final TilePropertyKey TREAT_AS_WALL_ORDER = TilePropertyKey.registerBase("TreatAsWallOrder");
    public static final TilePropertyKey TREE = TilePropertyKey.registerBase("tree");
    public static final TilePropertyKey TV = TilePropertyKey.registerBase("TV");
    public static final TilePropertyKey UNBREAKABLE_WINDOW_N = TilePropertyKey.registerBase("UnbreakableWindowN");
    public static final TilePropertyKey UNBREAKABLE_WINDOW_NW = TilePropertyKey.registerBase("UnbreakableWindowNW");
    public static final TilePropertyKey UNBREAKABLE_WINDOW_W = TilePropertyKey.registerBase("UnbreakableWindowW");
    public static final TilePropertyKey UNFLAMMABLE = TilePropertyKey.registerBase("unflammable");
    public static final TilePropertyKey UNLIT = TilePropertyKey.registerBase("unlit");
    public static final TilePropertyKey UNUSROOF_WALL_STARTD = TilePropertyKey.registerBase("RoofWallStart");
    public static final TilePropertyKey USE_OBJECT_DEPTH_TEXTURE = TilePropertyKey.registerBase("UseObjectDepthTexture");
    public static final TilePropertyKey VEGITATION = TilePropertyKey.registerBase("vegitation");
    public static final TilePropertyKey WALL = TilePropertyKey.registerBase("wall");
    public static final TilePropertyKey WALL_N = TilePropertyKey.registerBase("WallN");
    public static final TilePropertyKey WALL_NW = TilePropertyKey.registerBase("WallNW");
    public static final TilePropertyKey WALL_NW_TRANS = TilePropertyKey.registerBase("WallNWTrans");
    public static final TilePropertyKey WALL_N_TRANS = TilePropertyKey.registerBase("WallNTrans");
    public static final TilePropertyKey WALL_OBJECT_ALLOW_DOORFRAME = TilePropertyKey.registerBase("WallObjectAllowDoorframe");
    public static final TilePropertyKey WALL_OVERLAY = TilePropertyKey.registerBase("WallOverlay");
    public static final TilePropertyKey WALL_SE = TilePropertyKey.registerBase("WallSE");
    public static final TilePropertyKey WALL_TYPE = TilePropertyKey.registerBase("WallType");
    public static final TilePropertyKey WALL_W = TilePropertyKey.registerBase("WallW");
    public static final TilePropertyKey WALL_W_TRANS = TilePropertyKey.registerBase("WallWTrans");
    public static final TilePropertyKey WATER = TilePropertyKey.registerBase("water");
    public static final TilePropertyKey WATER_AMOUNT = TilePropertyKey.registerBase("waterAmount");
    public static final TilePropertyKey WATER_MAX_AMOUNT = TilePropertyKey.registerBase("waterMaxAmount");
    public static final TilePropertyKey WATER_PIPED = TilePropertyKey.registerBase("waterPiped");
    public static final TilePropertyKey WEST_ROOF_B = TilePropertyKey.registerBase("WestRoofB");
    public static final TilePropertyKey WEST_ROOF_M = TilePropertyKey.registerBase("WestRoofM");
    public static final TilePropertyKey WEST_ROOF_T = TilePropertyKey.registerBase("WestRoofT");
    public static final TilePropertyKey WHEELIE_BIN = TilePropertyKey.registerBase("WheelieBin");
    public static final TilePropertyKey WINDOW_FN = TilePropertyKey.registerBase("windowFN");
    public static final TilePropertyKey WINDOW_FW = TilePropertyKey.registerBase("windowFW");
    public static final TilePropertyKey WINDOW_LOCKED = TilePropertyKey.registerBase("WindowLocked");
    public static final TilePropertyKey WINDOW_N = TilePropertyKey.registerBase("WindowN");
    public static final TilePropertyKey WINDOW_W = TilePropertyKey.registerBase("WindowW");
    public static final TilePropertyKey WIND_TYPE = TilePropertyKey.registerBase("WindType");
    public static final TilePropertyKey W_OFFSET = TilePropertyKey.registerBase("Woffset");

    private TilePropertyKey() {
    }

    public static TilePropertyKey register(String id) {
        return TilePropertyKey.register(false, id);
    }

    private static TilePropertyKey registerBase(String id) {
        return TilePropertyKey.register(true, id);
    }

    private static TilePropertyKey register(boolean allowDefaultNamespace, String id) {
        return Registries.TILE_PROPERTY_KEY.register(RegistryReset.createLocation(id, allowDefaultNamespace), new TilePropertyKey());
    }

    public static TilePropertyKey get(ResourceLocation id) {
        return Registries.TILE_PROPERTY_KEY.get(id);
    }

    public String toString() {
        return Registries.TILE_PROPERTY_KEY.getLocation(this).toString();
    }
}

